version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: svelte-check
    versions:
    - 1.2.4
    - 1.2.5
    - 1.2.6
    - 1.3.0
    - 1.4.0
    - 1.5.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.17
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.8
  - dependency-name: "@types/marked"
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: svelte
    versions:
    - 3.35.0
    - 3.36.0
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.9
    - 4.7.0
  - dependency-name: marked
    versions:
    - 2.0.1
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.1
